name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Criterion
      run: |
        sudo apt-get update
        sudo apt-get install -y criterion-dev

    - name: make
      run: make
